# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Flow Log Processor

on:
  workflow_dispatch: # Enables manual triggering
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Generate Input Files
      run: |
        python3 generateSampleFiles.py --custom_sets minimal
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add flow_logs
        git commit -m "Add flow_logs to parent directory"
        git push
      

    - name: Run Flow Log Processor and move output file
      run: |
         mkdir -p output
         python3 flowLogProcessor.py flow_logs/flow_logs_mixed.txt mapping.csv output/output_mixed.txt --protocol_mapping_file protocolnumbers1.csv 
         python3 flowLogProcessor.py flow_logs/flow_logs_custom_minimal.txt mapping.csv output/output_custom_minimal.txt --log_field_names srcaddr dstaddr dstport protocol action --protocol_mapping_file protocolnumbers1.csv
         python3 flowLogProcessor.py flow_logs/flow_logs_v5.txt mapping.csv output/output_v5.txt --protocol_mapping_file protocolnumbers1.csv 
         python3 flowLogProcessor.py flow_logs/flow_logs_v3.txt mapping.csv output/output_v3.txt --protocol_mapping_file protocolnumbers1.csv  
         python3 flowLogProcessor.py flow_logs/flow_logs_v2.txt mapping.csv output/output_v3.txt --protocol_mapping_file protocolnumbers1.csv     
         git config --global user.email "actions@github.com"
         git config --global user.name "GitHub Actions"
         git add output
         git commit -m "Adding outputs to parent directory"
         git push
