name: Flow Log Processor

on:
  push:
    branches:
      - main 

jobs:
  run_processor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' 

      - name: Install dependencies (if any)
        run: |
          pip install -r requirements.txt # If you have a requirements.txt

      - name: Generate Input Files
        run: python generateSampleFiles.py

      - name: Run Flow Log Processor
        run: python flowLogProcessor.py flow_logs.txt mapping.csv output.txt

      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: output-file
          path: output.txt